name: "Deploy"

on:
  pull_request:
    types:
      - merged
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Deploy to my EC2 instance
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          SCRIPT_AFTER: |
            cd fastapi-book-project

            if [ -d '.venv' ]; then
              source .venv/bin/activate
            else
              python3 -m venv .venv
              source .venv/bin/activate
            fi

            pip install -r requirements.txt
            sudo systemctl restart books-api.service

            # Run the healthchecks to verify everything went well
            curl localhost:80/healthcheck ; echo
            echo "Deployed successfully"
