name: "Deploy"

on:
  pull_request:
    types:
      - merged

  deploy:
      name: Deploy to EC2 Instance
      runs-on: ubuntu-latest

      steps:
        - name: Checkout the code
          uses: actions/checkout@v2

        - name: Deploy to my EC2 instance
          uses: easingthemes/ssh-deploy@main
          env:
            SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
            SOURCE: "./"
            REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
            REMOTE_USER: ${{ secrets.REMOTE_USER }}
            TARGET: ${{ REMOTE_TARGET }}
